name: CI workflow

on: 
  push: 
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3  # Checkout the repository code

      - name: Use Node.js with yarn
        uses: actions/setup-node@v3
        with:
          node-version: 19.9.0 

      - name: Install dependencies
        run: yarn install

      - name: run test
        run: yarn run test
